version: "3"
services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: abcde
      POSTGRES_USER: jay
      POSTGRES_DB: kaguyasp
    volumes: 
      - "/media/fast/postgres:/var/lib/postgresql/data"
    ports:
        - "5432:5432"
#  admin:
#      image: jlaura/pgadmin4
#      restart: always
#      ports:
#          - "5050:5050"
