version: "3"
services:
  db:
    image: mdillon/postgis:9.6-alpine
    environment: 
      POSTGRES_PASSWORD: abcde
      POSTGRES_USER: jay
      POSTGRES_DB: kaguyasp
    volumes: 
      - "/media/fast/postgres:/var/lib/postgresql/data"
    ports:
        - "8001:5432"
  admin:
      image: jlaura/pgadmin4:0.2
      ports:
      - "5050:5050"
