version: "3"

services:
  master:
    image: jlaura/spark
    command: start-spark master
    hostname: master
    networks:
      - vnet
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "50070:50070"
  
  worker:
    image: jlaura/spark
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
    links:
      - master
    networks:
      - vnet

  jupyter:
    image: kelvinrr/jupyter-spark
    environment:
      NB_USER: 'jlaura'
    links:
      - master
    expose:
      - 8888
    ports:
      - 8888
    networks:
      - vnet
    volumes:
            - /data:/data


    command: jupyter lab --allow-root --NotebookApp.token=''

networks:
    vnet:
        external:
             name: vnet
